### ISSUE TITLE
Ongoing maintenance of this track.

### ISSUE THREAD

**Issue by redvers** [exercism/pony#124]
Greetings,

As I understand it, this track currently has no maintainer.  I spoke privately to the last maintainer (Theo) who told me that they stepped down several years ago and that it appears that nobody else has stepped up.

I would like to step up.  What do I need to do?

Thaks,

Red

**Comment by axtens** [comment]
Hello Red

Your best first step would be to get in touch with @ErikSchierboom  or @iHiD . When I took on the maintenance of vbnet it was Erik who provided the most guidance. Once part of the Exercism Slack community I was then able to draw heavily on the experience of other maintainers ahead of the Exercism V3 launch. Since then Erik has been indispensible in the launch of the COBOL track and in the development of the 8th (a FORTH variant) track.

Kind regards,
Bruce.

**Comment by iHiD** [comment]
@redvers This is exciting - thanks. @ErikSchierboom will reply next week to get you set up!

**Comment by redvers** [comment]
Thank you, I really appreciate your help. 

I have some reading to do to work out what is involved to get us up to spec.

**Comment by ErikSchierboom** [comment]
Hi @redvers! That sounds great. Pony lang is quite an interesting language and it would be great to have it added to Exercism.

Could you send an email to erik at exercism.org? I'll then help you get setup. Thanks!

**Comment by redvers** [comment]
@ErikSchierboom - sent this morning as requested.

Thanks.

**Comment by ErikSchierboom** [comment]
Great! I've sent you an email with a guide to getting the Pony track launched.

**Comment by redvers** [comment]
I think we have a working path now - thank you.
